# Generated by Django 3.2.3 on 2025-03-18 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='_accounts_user_follows_+', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
