# Generated by Django 3.2.3 on 2025-03-07 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_rename_auhtor_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
