# Generated by Django 3.2.3 on 2025-03-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='', upload_to='recipes/image', verbose_name='Изображение'),
        ),
    ]
