# Generated by Django 3.2.3 on 2025-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_link',
        ),
        migrations.AddField(
            model_name='recipe',
            name='url_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг для формирования короткой ссылки'),
        ),
    ]
